{{- if .Values.pool.enabled }}
{{- $global := . }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: {{ .Release.Name }}-block
   annotations:
     storageclass.beta.kubernetes.io/is-default-class: {{ .Values.storageclass.default | quote }}
provisioner: rook.io/block
parameters:
  pool: {{ .Values.pool.name | quote }}
  # Specify the Rook cluster from which to create volumes.
  # If not specified, it will use `rook` as the name of the cluster.
  # This is also the namespace where the cluster will be
  clusterName: {{ .Values.cluster.name | quote }}
  # Specify the filesystem type of the volume. If not specified, it will use `ext4`.
  # fstype: ext4
{{- end }}