apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    "app.kubernetes.io/name": {{ template "pyspark-notebook.name" . }}
    "helm.sh/chart": {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    "app.kubernetes.io/managed-by": {{ .Release.Service }}
    "app.kubernetes.io/instance": {{ .Release.Name }}
    "app.kubernetes.io/version": {{ .Chart.AppVersion }}
  name: {{ template "pyspark-notebook.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - http:
        paths:
        - pathType: ImplementationSpecific
          backend:
            service:
              name: {{ template "pyspark-notebook.jupyter.service.name" . }}
              port:
                number: {{ .Values.jupyter.externalPort }}
