{
 "title": "Rook - Cluster",
 "description": "Ceph Cluster overview.\r\n",
 "tags": [
  "ceph",
  "cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "CLUSTER STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "ceph_health_status" }
   ]
  },
  {
   "title": "Monitors In Quorum",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "ceph_mon_quorum_count" }
   ]
  },
  {
   "title": "Pools",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(ceph_pool_bytes_used)" }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "ceph_cluster_total_bytes" }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "ceph_cluster_total_used_bytes" }
   ]
  },
  {
   "title": "Available Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes/ceph_cluster_total_bytes"
    }
   ]
  },
  { "title": "OSD STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "OSDs IN",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(ceph_osd_in)" }
   ]
  },
  {
   "title": "OSDs OUT",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_osd_up) - count(ceph_osd_in)"
    }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(ceph_osd_up)" }
   ]
  },
  {
   "title": "OSDs DOWN",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_osd_up == 0) OR vector(0)"
    }
   ]
  },
  {
   "title": "Agerage PGs per OSD",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "avg(ceph_osd_numpg)" }
   ]
  },
  {
   "title": "Average OSD Apply Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    { "expr": "avg(ceph_osd_apply_latency_ms)" }
   ]
  },
  {
   "title": "Average OSD Commit Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(ceph_osd_commit_latency_ms)"
    }
   ]
  },
  {
   "title": "Average Monitor Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(ceph_monitor_latency_seconds)"
    }
   ]
  },
  { "title": "CLUSTER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Capacity",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes-ceph_cluster_total_used_bytes",
     "legendFormat": "Available"
    },
    { "expr": "ceph_cluster_total_used_bytes", "legendFormat": "Used" },
    { "expr": "ceph_cluster_total_bytes", "legendFormat": "Total Capacity" }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ceph_osd_op_r[$interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(ceph_osd_op_w[$interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Throughtoutput",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_r_out_bytes[$interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(irate(ceph_osd_op_w_in_bytes[$interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  { "title": "LATENCY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "OSD Apply + Commit Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "avg(ceph_osd_apply_latency_ms)", "legendFormat": "apply" },
    {
     "expr": "avg(ceph_osd_commit_latency_ms)",
     "legendFormat": "commit"
    }
   ]
  },
  {
   "title": "Monitor Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(ceph_monitor_latency_seconds)",
     "legendFormat": "latency"
    }
   ]
  },
  { "title": "OBJECTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Objects in the Cluster",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_cluster_total_objects", "legendFormat": "Total" }
   ]
  },
  {
   "title": "PGs",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_pg_active", "legendFormat": "Active" },
    { "expr": "ceph_pg_clean", "legendFormat": "Clean" },
    { "expr": "ceph_pg_peering", "legendFormat": "Peering" },
    { "expr": "ceph_pg_degraded", "legendFormat": "Degraded" },
    { "expr": "ceph_pg_stale", "legendFormat": "Stale" },
    { "expr": "ceph_unclean_pgs", "legendFormat": "Unclean" },
    { "expr": "ceph_pg_undersized", "legendFormat": "Undersized" },
    { "expr": "ceph_pg_incomplete", "legendFormat": "Incomplete" },
    { "expr": "ceph_pg_forced_backfill", "legendFormat": "Forced Backfill" },
    { "expr": "ceph_pg_inconsistent", "legendFormat": "Inconsistent" },
    { "expr": "ceph_pg_forced_recovery", "legendFormat": "Forced Recovery" },
    { "expr": "ceph_pg_creating", "legendFormat": "Creating" },
    { "expr": "ceph_pg_wait_backfill", "legendFormat": "Wait Backfill" },
    { "expr": "ceph_pg_deep", "legendFormat": "Deep" },
    { "expr": "ceph_pg_scrubbing", "legendFormat": "Scrubbing" },
    { "expr": "ceph_pg_recovering", "legendFormat": "Recovering" },
    { "expr": "ceph_pg_repair", "legendFormat": "Repair" },
    { "expr": "ceph_pg_down", "legendFormat": "Down" },
    { "expr": "ceph_pg_peered", "legendFormat": "Peered" },
    { "expr": "ceph_pg_backfill", "legendFormat": "Backfill" },
    { "expr": "ceph_pg_remapped", "legendFormat": "Remapped" },
    { "expr": "ceph_pg_backfill_toofull", "legendFormat": "Backfill Toofull" }
   ]
  },
  {
   "title": "Stuck PGs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_pg_degraded", "legendFormat": "Degraded" },
    { "expr": "ceph_pg_stale", "legendFormat": "Stale" },
    { "expr": "ceph_pg_undersized", "legendFormat": "Undersized" }
   ]
  },
  { "title": "RECOVERY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Operations",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_recovery_ops[$interval]))",
     "legendFormat": "OPS"
    }
   ]
  }
 ]
}